### ISSUE TITLE
请问数字emoji显示异常如何解决？

### ISSUE THREAD

**Issue by isyngo** [zuoez02/siyuan-plugin-twitter-emoji#1]
你好，部分数字的emoji无法正常显示，请问要如何操作？

操作系统：win10
软件版本：2.9.0
插件版本：0.1.0

![Snipaste_2023-06-11_19-07-22](https://github.com/zuoez02/siyuan-plugin-twitter-emoji/assets/8169006/61c0fc25-92a0-4c9c-9360-2e884c2164dd)

**Comment by zuoez02** [comment]
twitter的emoji里面没有数字？或者说这个不标准所以官方没有适配的问题

**Comment by isyngo** [comment]
Twitter官方emoji项目里面有数字，地址如下：
https://github.com/twitter/twemoji/blob/master/assets/svg/30-20e3.svg
https://github.com/twitter/twemoji/blob/master/assets/svg/31-20e3.svg
https://github.com/twitter/twemoji/blob/master/assets/svg/32-20e3.svg
https://github.com/twitter/twemoji/blob/master/assets/svg/33-20e3.svg
https://github.com/twitter/twemoji/blob/master/assets/svg/34-20e3.svg
https://github.com/twitter/twemoji/blob/master/assets/svg/35-20e3.svg
https://github.com/twitter/twemoji/blob/master/assets/svg/36-20e3.svg
https://github.com/twitter/twemoji/blob/master/assets/svg/37-20e3.svg
https://github.com/twitter/twemoji/blob/master/assets/svg/38-20e3.svg
https://github.com/twitter/twemoji/blob/master/assets/svg/39-20e3.svg

之前思源没有取消特性时是正常的。请问是思源软件的问题，还是操作系统的问题？

**Comment by zuoez02** [comment]
不像操作系统的问题，我在mac里也这样

**Comment by zuoez02** [comment]
https://github.com/mozilla/twemoji-colr/issues/56 这个是引用的字体，他们也有这个问题，里面的临时解决方案并不奏效

**Comment by isyngo** [comment]
好的，谢谢了

**Comment by aobatu** [comment]
想问下这个问题最后大家是怎么解决的？

**Comment by zuoez02** [comment]
解决不了，字体集里缺失这些东西，建议用另外一个emoji插件
